# Generated by Django 5.0.6 on 2024-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_rename_add_at_category_add_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                default="category.jgp", upload_to="media/category_image"
            ),
        ),
    ]
