# Generated by Django 5.0.6 on 2024-05-13 05:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                editable=False,
                length=16,
                max_length=40,
                prefix="Cat-",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
