# Generated by Django 5.0.6 on 2024-05-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorite", "0002_rename_add_at_favorite_add_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoriteitem",
            old_name="Favorite",
            new_name="favorite",
        ),
    ]
