# Generated by Django 5.0.6 on 2024-05-09 12:32

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        length=16,
                        max_length=40,
                        prefix="Prod-",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="untitle product", max_length=50)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField()),
                ("price", models.IntegerField()),
                ("promo_price", models.IntegerField(blank=True, null=True)),
                ("add_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
