# Generated by Django 5.0.6 on 2024-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_add_at_product_add_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                default="product.jgp", upload_to="media/Product_image"
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.FileField(
                default="product.jgp", upload_to="media/Product_image"
            ),
        ),
    ]
