# Generated by Django 5.0.6 on 2024-05-09 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_consumer_image_vendor_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(default="not set", max_length=500)),
                ("phone", models.PositiveIntegerField()),
                ("verifed", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer",
                        to="userprofile.consumer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to="userprofile.vendor",
                    ),
                ),
            ],
        ),
    ]
