# Generated by Django 5.0.6 on 2024-05-09 23:24

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_rename_id_user_uid_alter_address_consumer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                editable=False,
                length=4,
                max_length=20,
                prefix="user-",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
