# Generated by Django 5.0.6 on 2024-05-09 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_rename_uid_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="verifed",
            new_name="verified",
        ),
        migrations.RemoveField(
            model_name="address",
            name="consumer",
        ),
        migrations.RemoveField(
            model_name="address",
            name="vendor",
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
