# Generated by Django 5.0.6 on 2024-05-09 23:49

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_rename_verifed_address_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                editable=False,
                length=4,
                max_length=20,
                prefix="user-",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
