# Generated by Django 5.0.6 on 2024-05-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_user_uid_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.AddField(
            model_name="address",
            name="consumer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer",
                to="userprofile.consumer",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="userprofile.vendor",
            ),
        ),
    ]
