# Generated by Django 5.0.6 on 2024-05-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_remove_address_user_address_consumer_address_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumer",
            old_name="add_at",
            new_name="add",
        ),
        migrations.RenameField(
            model_name="vendor",
            old_name="add_at",
            new_name="add",
        ),
    ]
